# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Mon Nov 28 11:04:01 2016
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(689, 482)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_9 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_9.setObjectName("groupBox_9")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_9)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.pushButton_InfReadInformation = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_InfReadInformation.setObjectName("pushButton_InfReadInformation")
        self.horizontalLayout_9.addWidget(self.pushButton_InfReadInformation)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_9)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.progressBarInfRead = QtWidgets.QProgressBar(self.groupBox_9)
        self.progressBarInfRead.setProperty("value", 0)
        self.progressBarInfRead.setObjectName("progressBarInfRead")
        self.horizontalLayout_9.addWidget(self.progressBarInfRead)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_9)
        self.label_27 = QtWidgets.QLabel(self.groupBox_9)
        self.label_27.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.lineEdit_R_InstrumentNumber = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_R_InstrumentNumber.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_R_InstrumentNumber.setFont(font)
        self.lineEdit_R_InstrumentNumber.setObjectName("lineEdit_R_InstrumentNumber")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_R_InstrumentNumber)
        self.label_3 = QtWidgets.QLabel(self.groupBox_9)
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_R_UserNumber = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_R_UserNumber.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_R_UserNumber.setFont(font)
        self.lineEdit_R_UserNumber.setObjectName("lineEdit_R_UserNumber")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_R_UserNumber)
        self.label_28 = QtWidgets.QLabel(self.groupBox_9)
        self.label_28.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.lineEdit_R_InstrumentDate = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_R_InstrumentDate.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_R_InstrumentDate.setFont(font)
        self.lineEdit_R_InstrumentDate.setObjectName("lineEdit_R_InstrumentDate")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_R_InstrumentDate)
        self.label_24 = QtWidgets.QLabel(self.groupBox_9)
        self.label_24.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.lineEdit_R_IntervalTime = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_R_IntervalTime.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_R_IntervalTime.setFont(font)
        self.lineEdit_R_IntervalTime.setObjectName("lineEdit_R_IntervalTime")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_R_IntervalTime)
        self.label_26 = QtWidgets.QLabel(self.groupBox_9)
        self.label_26.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.lineEdit_R_DoseThreshold = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_R_DoseThreshold.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.lineEdit_R_DoseThreshold.setFont(font)
        self.lineEdit_R_DoseThreshold.setObjectName("lineEdit_R_DoseThreshold")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_R_DoseThreshold)
        self.label_25 = QtWidgets.QLabel(self.groupBox_9)
        self.label_25.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.lineEdit_R_DoseRateThreshold = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_R_DoseRateThreshold.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_R_DoseRateThreshold.setFont(font)
        self.lineEdit_R_DoseRateThreshold.setObjectName("lineEdit_R_DoseRateThreshold")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit_R_DoseRateThreshold)
        self.label = QtWidgets.QLabel(self.groupBox_9)
        self.label.setObjectName("label")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit_R_MaximumDoseRate = QtWidgets.QLineEdit(self.groupBox_9)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.lineEdit_R_MaximumDoseRate.setFont(font)
        self.lineEdit_R_MaximumDoseRate.setObjectName("lineEdit_R_MaximumDoseRate")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit_R_MaximumDoseRate)
        self.label_4 = QtWidgets.QLabel(self.groupBox_9)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_R_MaximumDoseRateTime = QtWidgets.QLineEdit(self.groupBox_9)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.lineEdit_R_MaximumDoseRateTime.setFont(font)
        self.lineEdit_R_MaximumDoseRateTime.setObjectName("lineEdit_R_MaximumDoseRateTime")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lineEdit_R_MaximumDoseRateTime)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        self.label_5 = QtWidgets.QLabel(self.groupBox_9)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_R_CumulativeDose = QtWidgets.QLineEdit(self.groupBox_9)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.lineEdit_R_CumulativeDose.setFont(font)
        self.lineEdit_R_CumulativeDose.setObjectName("lineEdit_R_CumulativeDose")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.lineEdit_R_CumulativeDose)
        self.gridLayout_2.addWidget(self.groupBox_9, 1, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_OpenSerial = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_OpenSerial.setEnabled(True)
        self.pushButton_OpenSerial.setObjectName("pushButton_OpenSerial")
        self.horizontalLayout_2.addWidget(self.pushButton_OpenSerial)
        self.comboBox_ComNum = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_ComNum.setObjectName("comboBox_ComNum")
        self.horizontalLayout_2.addWidget(self.comboBox_ComNum)
        self.pushButton_UpdateSerialShow = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_UpdateSerialShow.setObjectName("pushButton_UpdateSerialShow")
        self.horizontalLayout_2.addWidget(self.pushButton_UpdateSerialShow)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem4, 0, 0, 1, 1)
        self.lineEdit_InstrumentFactoryNumber = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_InstrumentFactoryNumber.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_InstrumentFactoryNumber.setFont(font)
        self.lineEdit_InstrumentFactoryNumber.setObjectName("lineEdit_InstrumentFactoryNumber")
        self.gridLayout.addWidget(self.lineEdit_InstrumentFactoryNumber, 1, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 1, 2, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 2)
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setObjectName("groupBox_7")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_7)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.pushButton_Style = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_Style.setObjectName("pushButton_Style")
        self.horizontalLayout_8.addWidget(self.pushButton_Style)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.pushButton_InfWriteInformation = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_InfWriteInformation.setObjectName("pushButton_InfWriteInformation")
        self.horizontalLayout_8.addWidget(self.pushButton_InfWriteInformation)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.label_9 = QtWidgets.QLabel(self.groupBox_7)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.progressBarInfWrite = QtWidgets.QProgressBar(self.groupBox_7)
        self.progressBarInfWrite.setProperty("value", 0)
        self.progressBarInfWrite.setObjectName("progressBarInfWrite")
        self.horizontalLayout_8.addWidget(self.progressBarInfWrite)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_8)
        self.label_16 = QtWidgets.QLabel(self.groupBox_7)
        self.label_16.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.lineEdit_W_InstrumentNumber = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_W_InstrumentNumber.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.lineEdit_W_InstrumentNumber.setFont(font)
        self.lineEdit_W_InstrumentNumber.setObjectName("lineEdit_W_InstrumentNumber")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_W_InstrumentNumber)
        self.label_2 = QtWidgets.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_W_UserNumber = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_W_UserNumber.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_W_UserNumber.setFont(font)
        self.lineEdit_W_UserNumber.setObjectName("lineEdit_W_UserNumber")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_W_UserNumber)
        self.label_18 = QtWidgets.QLabel(self.groupBox_7)
        self.label_18.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.lineEdit_W_InstrumentDate = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_W_InstrumentDate.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_W_InstrumentDate.setFont(font)
        self.lineEdit_W_InstrumentDate.setObjectName("lineEdit_W_InstrumentDate")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_W_InstrumentDate)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(13, QtWidgets.QFormLayout.SpanningRole, spacerItem8)
        self.label_19 = QtWidgets.QLabel(self.groupBox_7)
        self.label_19.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.label_14 = QtWidgets.QLabel(self.groupBox_7)
        self.label_14.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.lineEdit_W_DoseThreshold = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_W_DoseThreshold.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_W_DoseThreshold.setFont(font)
        self.lineEdit_W_DoseThreshold.setObjectName("lineEdit_W_DoseThreshold")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_W_DoseThreshold)
        self.lineEdit_W_DoseRateThreshold = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_W_DoseRateThreshold.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_W_DoseRateThreshold.setFont(font)
        self.lineEdit_W_DoseRateThreshold.setObjectName("lineEdit_W_DoseRateThreshold")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit_W_DoseRateThreshold)
        self.label_15 = QtWidgets.QLabel(self.groupBox_7)
        self.label_15.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.lineEdit_W_CumulativeDoseReset = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_W_CumulativeDoseReset.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_W_CumulativeDoseReset.setFont(font)
        self.lineEdit_W_CumulativeDoseReset.setObjectName("lineEdit_W_CumulativeDoseReset")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lineEdit_W_CumulativeDoseReset)
        self.label_12 = QtWidgets.QLabel(self.groupBox_7)
        self.label_12.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.lineEdit_W_IntervalTime = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_W_IntervalTime.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_W_IntervalTime.setFont(font)
        self.lineEdit_W_IntervalTime.setObjectName("lineEdit_W_IntervalTime")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_W_IntervalTime)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(0, QtWidgets.QFormLayout.LabelRole, spacerItem9)
        self.gridLayout_2.addWidget(self.groupBox_7, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_9.setTitle(_translate("MainWindow", "读取信息"))
        self.pushButton_InfReadInformation.setText(_translate("MainWindow", "获取信息"))
        self.label_10.setText(_translate("MainWindow", "读取进度："))
        self.label_27.setText(_translate("MainWindow", "仪器编号"))
        self.label_3.setText(_translate("MainWindow", "用户编号"))
        self.label_28.setText(_translate("MainWindow", "仪器日期"))
        self.label_24.setText(_translate("MainWindow", "间隔时间存储(s)"))
        self.label_26.setText(_translate("MainWindow", "剂量阈值(uSv)"))
        self.label_25.setText(_translate("MainWindow", "剂量率阈值(uSv/h)"))
        self.label.setText(_translate("MainWindow", "最大剂量率(uSv/h)"))
        self.label_4.setText(_translate("MainWindow", "最大剂量率时刻"))
        self.label_5.setText(_translate("MainWindow", "累积剂量"))
        self.groupBox.setTitle(_translate("MainWindow", "串口操作"))
        self.pushButton_OpenSerial.setText(_translate("MainWindow", "打开串口"))
        self.pushButton_UpdateSerialShow.setText(_translate("MainWindow", "更新串口"))
        self.label_17.setText(_translate("MainWindow", "仪器出厂编号："))
        self.groupBox_7.setTitle(_translate("MainWindow", "配置信息"))
        self.pushButton_Style.setText(_translate("MainWindow", "参考格式"))
        self.pushButton_InfWriteInformation.setText(_translate("MainWindow", "开始配置"))
        self.label_9.setText(_translate("MainWindow", "配置进度："))
        self.label_16.setText(_translate("MainWindow", "仪器编号"))
        self.label_2.setText(_translate("MainWindow", "用户编号"))
        self.label_18.setText(_translate("MainWindow", "仪器日期"))
        self.label_19.setText(_translate("MainWindow", "剂量阈值(uSv)"))
        self.label_14.setText(_translate("MainWindow", "剂量率阈值(uSv/h)"))
        self.label_15.setText(_translate("MainWindow", "累积剂量清零"))
        self.label_12.setText(_translate("MainWindow", "间隔时间存储(s)"))

